### ISSUE TITLE
Add repo but got index.yaml not found

### ISSUE THREAD

**Issue by thomsonnapitupulu** [opencost/opencost-helm-chart#20]
**Step to reproduce:**

1. I put these lines in Terraform:

> ```
> resource "helm_release" "opencost" {
>   atomic           = "true"
>   name             = "opencost"
>   version          = "1.100.0"
>   namespace        = "opencost"
>   create_namespace = "true"
>   repository       = "https://opencost.github.io/opencost-helm-chart"
>   chart            = "opencost"
> 
>   values = [
>     file("helm_values/opencost.values.yaml")
>   ]
> }
> ```

2. Then I do `tf-apply` 

**Actual result:**
I got error "index.yaml not found"

**Expected result:** 
The index.yaml file exists and accessible so adding repo get success.
Mostly repo have accessible index.yaml, for example:
https://kubecost.github.io/cost-analyzer/index.yaml

**Screenshot:**
<img width="947" alt="Screen Shot 2023-02-23 at 16 42 14" src="https://user-images.githubusercontent.com/7758567/220871434-c184081b-bdd8-4b51-b41d-62bdc25f2927.png">

**Comment by toscott** [comment]
Confirmed. 
I suspect the github page is using 'main' instead of the 'gh-pages' branch.

We will have to get @mattray to swap that back for us. 

Should look like this.
![Screen Shot 2023-02-24 at 9 27 57 PM](https://user-images.githubusercontent.com/2982533/221333889-4976bec6-99b4-46e3-8c91-a78ed895aa10.png)

**Comment by mattray** [comment]
Set it to `gh-pages`
