### ISSUE TITLE
Change merge strategy to "squash merging" 

### ISSUE THREAD

**Issue by mkilchhofer** [opencost/opencost-helm-chart#34]
Hi everybody

I already asked for this in the slack channel #opencost.
<img width="545" alt="grafik" src="https://user-images.githubusercontent.com/7290987/225110972-c02f4b1f-e127-471c-a8e8-07397abd33cb.png">

As I am one of the maintainer of the Argo CD helm repository, we follow what most chart repositories do:
<img width="824" alt="grafik" src="https://user-images.githubusercontent.com/7290987/225110789-bbdf31c2-b076-4ae0-8672-a714f2a7c113.png">

Can you change this as well here?

/cc: @sntxrr @Pokom

**Comment by mattray** [comment]
I generally don’t use squash merges, but if everyone else does I don’t care enough not to allow them. Anyone feel strongly against them? @dwbrown2 @Pokom @AjayTripathy @toscott any opinions yeah/nay?

**Comment by Pokom** [comment]
I would prefer that we allow it. Squashing vs Merging will usually turn into a divisive topic, so I don't want to push it unless we're all in agreement.

My primary reason for doing a squash commit is that it keeps the history clean on `main`. However, the challenge because if one of those small commits that got squashed has an issue, we need to revert the entire change if it's squashed.

I'd say let's vote with :+1: and :-1: on the main issue to get consensus.

**Comment by mattray** [comment]
Updated to match screenshot.

**Comment by AjayTripathy** [comment]
If squash is what the community does I support that!
